# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RxTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxTableView
  pod "RxSwift", "~> 5.0"
  pod "RxCocoa", "~> 5.0"
  pod "RxDataSources", "~> 4.0"

end
